### ISSUE TITLE
Headless not moving on from boss tile.

### ISSUE THREAD

**Issue by MetaHerobrine1** [meepen/salien-bot#163] opened 2018-06-30 23:46 UTC
I'm using the -e flag and for some reason the bot is getting hung up on the ReportBossDamage section of the API.  I'm using version 2.1.5 and I've also attached the log file in case it helps.
[log.txt](https://github.com/meepen/salien-bot/files/2152272/log.txt)

**Comment by ahakola** [comment] 2018-07-01 00:06
Probably caused by this bug: #162 
Either restart the script or manually add that fix and redeploy the script for future proofing until @meepen commits this (or other fix to this problem) to the master.

**Comment by meepen** [comment] 2018-07-01 13:11
should be fixed on master

**Closed by meepen** 2018-07-01 13:11 UTC
