### ISSUE TITLE
Cant get any Xp 

### ISSUE THREAD

**Issue by tiago199988** [meepen/salien-bot#81] opened 2018-06-23 13:30 UTC
I cant get any xp i got the cards but no xp 
https://media.discordapp.net/attachments/327531611434516482/460065409484193822/unknown.png

**Comment by callmenemo491** [comment] 2018-06-23 13:39
duplicate of: #63, #74

**Comment by tiago199988** [comment] 2018-06-23 13:49
yes i know its duplicate but why its hapening ???

**Comment by callmenemo491** [comment] 2018-06-23 14:32
better for you to ask your question (why it happen) into ticket #75,
and close this one.

**Closed** 2018-06-23 19:22 UTC
